### Exercise 1: 

GET http://localhost:3000/

GET http://localhost:3000/about


### Exercise 2:
GET http://localhost:3000/todos

GET http://localhost:3000/todos/1

POST http://localhost:3000/todos
Content-Type: application/json

{
  "title": "Learn Express.js",
  "description": "Study routing and middleware",
  "completed": false
}

POST http://localhost:3000/todos
Content-Type: application/json

{
  "title": "Build REST API",
  "description": "Create CRUD operations",
  "completed": true
}

PUT http://localhost:3000/todos/1
Content-Type: application/json

{
  "title": "Learn Express.js with ES modules",
  "completed": true
}

PUT http://localhost:3000/todos/2
Content-Type: application/json

{
  "completed": false
}

DELETE http://localhost:3000/todos/1

GET http://localhost:3000/todos/999

PUT http://localhost:3000/todos/999
Content-Type: application/json

{
  "title": "This should fail"
}

DELETE http://localhost:3000/todos/999

POST http://localhost:3000/todos
Content-Type: application/json

{
  "description": "This should fail without title"
}